#markdown: rdiscount
permalink: /:title/
url: http://runylin.github.io
#highlighter: pygments
highlighter: rouge
gems: [jekyll-paginate]
paginate: 100
paginate_path: "page:num"
name: Blog | 林X土
description: 林X土的博客 | Keep Moving.
author: runylin
email: runylin@gmail.com
duoshuo: runylin
weibo: 1720075687
hub: runylin
safe: false
about: "菜鸡"
