#markdown: rdiscount
permalink: /:title/
url: http://github.runylin.com
#highlighter: pygments
highlighter: rouge
gems: [jekyll-paginate]
paginate: 100
paginate_path: "page:num"
name: 林X土实验室
description: 林X土实验室 | Keep Moving.
author: runylin
email: runylin@gmail.com
duoshuo: runylin
weibo: 1720075687
hub: runylin
safe: false
about: "菜鸡"
